#!/bin/bash -ei


tput civis

ptime() {
  clear
  date +"%H : %M" | figlet -w $center -c -f script 
  date +"%m / %d / %y" | figlet -w $center -c -f script
  stty -echo
  sleep 60	
}

trap "tput cvvis & echo 'Exited.'" EXIT

while true; do
stty echo &
ptime; done
