#!/bin/bash

export ORANGE=$(tput setaf 3)
export RED=$(tput setaf 1)
export BLUE=$(tput setaf 4)
export GREEN=$(tput setaf 2)
export PINK=$(tput setaf 5)
export STOP=$(tput sgr0)

pcolor() {

export PGREEN="2"
export PBLUE="4"

case $1 in
  green) export PCOLOR=$PGREEN && echo 'export PCOLOR="$GREEN"' >> ~/.config/zsh/zsh-data/zsh-colors ;;
  blue) export PCOLOR=$PBLUE && echo 'export PCOLOR="$BLUE"' >> ~/.config/zsh/zsh-data/zsh-colors ;;
esac

}


if [ ! -f ~/.config/zsh/zsh-data/zsh-colors ]; then

clear
echo "Prompt Color"

trap '' 2  

printf "
(1)  Blue

$(tput setaf 4)~/dotfiles$(tput sgr0) on $(tput setaf 5) main $(tput setaf 2)✔$(tput sgr0)                                 took 5s  1:40
$(tput setaf 4)$PROMPTCHAR$(tput sgr0)


(2)  Green

$(tput setaf 2)~/dotfiles$(tput sgr0) on $(tput setaf 5) main $(tput setaf 2)✔$(tput sgr0)                                 took 5s  1:40
$(tput setaf 2)$PROMPTCHAR$(tput sgr0) 
"

printf '
You can change the prompt color later with "pcolor green/blue"
Enter your selection:  '
read -r promptcolor
if [[ "$promptcolor" = "1" ]];
then
  echo 'export PCOLOR="$BLUE"' >> ~/.config/zsh/zsh-data/zsh-colors 
  clear
elif [[ "$promptcolor" = "2" ]];
then
  echo 'export PCOLOR="$GREEN"' >> ~/.config/zsh/zsh-data/zsh-colors 
  clear
else
  ~/.config/zsh/zsh-functions/startup
fi

trap 2

fi
